# Generated by Django 6.0.3 on 2026-03-28 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('steps_to_reproduce', models.TextField()),
                ('tester_id', models.CharField(max_length=100)),
                ('tester_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('New', 'New'), ('Open', 'Open'), ('Assigned', 'Assigned'), ('Fixed', 'Fixed'), ('Resolved', 'Resolved'), ('Rejected', 'Rejected'), ('Duplicate', 'Duplicate'), ('Cannot Reproduce', 'Cannot Reproduce'), ('Reopened', 'Reopened')], default='New', max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('Critical', 'Critical'), ('Major', 'Major'), ('Minor', 'Minor'), ('Low', 'Low')], max_length=20, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='defects.defectreport')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('defect_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='defects.defectreport')),
            ],
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='defectreport',
            name='assigned_developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_defects', to='defects.developer'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owned_product', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='developer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developers', to='defects.product'),
        ),
        migrations.AddField(
            model_name='defectreport',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_reports', to='defects.product'),
        ),
    ]
