# Generated by Django 6.0.3 on 2026-03-29 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defectreport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defectreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_defects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='defectreport',
            name='backlog_item_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
