# Generated by Django 5.2.5 on 2026-04-13 04:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0003_defectreport_rejected_at_defectreport_rejected_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defectreport',
            name='reopen_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defectreport',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defectreport',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_defects', to=settings.AUTH_USER_MODEL),
        ),
    ]
