# Generated by Django 5.2.5 on 2026-04-13 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0004_defectreport_reopen_reason_defectreport_reopened_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='defectreport',
            name='cannot_reproduce_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defectreport',
            name='cannot_reproduced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defectreport',
            name='cannot_reproduced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cannot_reproduced_defects', to='defects.employee'),
        ),
    ]
