# Generated by Django 5.2.5 on 2026-04-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0003_remove_product_owner_employee_and_more'),
        ('defects', '0005_defectreport_cannot_reproduce_reason_and_more'),
    ]

    operations = []
